export const SHOW_SEARCH ='HEADER/SHOW_SEARCH';
export const ClOSE_SEARCH='HEADER/ClOSE_SEARCH';
export const GET_HEADERLIST='HEADER/GET_HEADER_LIST';
export const MOUSEENTER='HEADER/MOUSE_ENTER';
export const MOUSELEAVE='HEADER/MOUSE_LEAVE';
export const UPGAPE='HEADER/UPGAPE';
